config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  resources :recipes, only: [:create, :index, :destroy, :show, :new, :update] do 
    member do
      patch 'update_privacy', to: 'recipes#update_privacy', as: 'update_recipe_privacy'
      get '/shopping_list', to:'recipes#shopping_list', as: :shopping_list
    end
  end

  resources :recipe_foods, only: [:new, :create, :destroy]

  resources :inventories, only: [:create, :index, :show, :destroy, :new] do
    resources :inventory_foods, only: [:new, :create, :destroy]
  end

  resources :inventory_foods do
    delete 'remove_food', on: :member
  end

  get '/public_recipes', to:'recipes#public_recipes', as: :public_recipes

  resources :foods, only: [:index, :create, :destroy, :new]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "recipes#public_recipes"
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true

  belongs_to :user, foreign_key: 'user_id'
  has_many :inventory_foods
  has_many :foods, through: :inventory_foods
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ability

  def set_ability
    @ability = Ability.new(current_user)
  end

  def new; end

  def index
    @inventories = Inventory.where(user_id: current_user.id)
  end

  def show
    @inventory = Inventory.includes(inventory_foods: :food).find(params[:id])
  end

  def destroy
    Inventory.find(params[:id]).destroy
    redirect_to inventories_path, notice: 'Inventory deleted'
  end

  def create
    @inventory = Inventory.new(inventory_params)
    @inventory.user_id = current_user.id

    if @inventory.save
      redirect_to inventories_path, notice: 'Inventory successfully added'
    else
      render :new, notice: 'Failed'
    end
  end

  private

  def inventory_params
    params.permit(:name, :description)
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/index.html.erb
<div class="text-center">
  <h1 class="text-4xl font-bold text-black my-8">Welcome To Inventory Page</h1>
</div>

<div class="flex flex-col items-center mt-2">
  <div class="w-full max-w-md">
    <div class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded text-center mb-4">
      <%= link_to 'Create New Inventory', new_inventory_path %>
    </div>
  </div>
  <div class="inventory-list w-full max-w-xl">
    <% @inventories.each do |inv| %>
      <div class="inventory bg-white shadow-md p-4 rounded-lg my-4">
        <%= link_to inventory_path(inv), class: "inventory-link" do %>
          <div class="header">
            <h2 class="text-xl font-bold text-blue-500 mb-2"><%= inv.name %></h2>
          </div>
          <div class="description">
            <p class="text-gray-600"><%= inv.description %></p>
          </div>
        <% end %>
        <div class="remove-button text-center mt-4">
          <%= form_with model: inv, url: inventory_path(inv), method: :delete do |form| %>
            <%= form.submit "Remove", class: "bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/inventories/new.html.erb
<div class="new-inventory max-w-md mx-auto mt-8 bg-white p-4 rounded-lg shadow-md">
  <h2 class="text-2xl font-bold text-blue-500 mb-4">Add Inventory</h2>
  <div class="new-body">
    <%= form_with model: @inventory, url: inventories_path do |f| %>
      <div class="mb-4">
        <%= f.label :name, class: "block text-gray-600 text-sm font-semibold" %>
        <%= f.text_field :name, class: "w-full p-2 border border-gray-300 rounded focus:ring-2 focus:ring-blue-500" %>
      </div>
      
      <div class="mb-4">
        <%= f.label :description, class: "block text-gray-600 text-sm font-semibold" %>
        <%= f.text_area :description, rows: 4, class: "w-full p-2 border border-gray-300 rounded focus:ring-2 focus:ring-blue-500" %>
      </div>
      
      <div class="text-center">
        <%= f.submit "Create Inventory", class: "bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 font-semibold" %>
      </div>
    <% end %>
  </div>
</div>

app/views/inventories/show.html.erb
<% if can? :read, @inventory%>
<div class="show-inventory max-w-3xl mx-auto mt-8 bg-white p-4 rounded-lg shadow-md">
  <h2 class="text-2xl font-semibold text-blue-500 mb-4"><%= @inventory.name %></h2>
  <div class="food-add">
    <%= link_to "Add Inventory Food", new_inventory_inventory_food_path(@inventory), class: "bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"%>
  </div>
  <div class="flex flex-col mt-4">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
            <div class="overflow-hidden">
                <table class="min-w-full text-left text-sm font-light">
                    <thead class="border-b font-medium dark:border-neutral-500">
                        <tr>
                            <th scope="col" class="px-6 py-3">Food</th>
                            <th scope="col" class="px-6 py-3">Quantity</th>
                            <% if can? :destroy, @inventory %>
                              <th scope="col" class="px-6 py-3">Actions</th>
                            <% end %>
                        </tr>
                    </thead>
                    <tbody>
                    <% @inventory.inventory_foods.each do |food| %>
                        <tr
                          class="border-b transition duration-300 ease-in-out hover:bg-neutral-100 dark:border-neutral-500 dark:hover:bg-neutral-600"
                        >
                          <td class="whitespace-nowrap px-6 py-4"><%= food.food.name %></td>
                          <td class="whitespace-nowrap px-6 py-4"><%= food.quantity %> <%= food.food.measurement_unit %></td>
                          <td class="whitespace-nowrap px-6 py-4 cursor-pointer">
                          <% if can? :destroy, @inventory %>
                          <%= form_with(model: food, url: inventory_food_path(food), method: :delete) do |form| %>
                            <%= form.submit "Remove", class: "text-blue-500 hover:underline" %>
                          <% end %>
                          <% end %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
  </div>
</div>
<% end %>
</div>