config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  resources :recipes, only: [:create, :index, :destroy, :show, :new, :update] do 
    member do
      patch 'update_privacy', to: 'recipes#update_privacy', as: 'update_recipe_privacy'
      get '/shopping_list', to:'recipes#shopping_list', as: :shopping_list
    end
  end

  resources :recipe_foods, only: [:new, :create, :destroy]

  resources :inventories, only: [:create, :index, :show, :destroy, :new] do
    resources :inventory_foods, only: [:new, :create, :destroy]
  end

  resources :inventory_foods do
    delete 'remove_food', on: :member
  end

  get '/public_recipes', to:'recipes#public_recipes', as: :public_recipes

  resources :foods, only: [:index, :create, :destroy, :new]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "recipes#public_recipes"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true

  def total_price
    total = 0
    recipe_foods.each do |r_food|
      total += (r_food.quantity * r_food.food.price)
    end
    total
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: %i[public_recipes show]
  before_action :set_ability

  def set_ability
    @ability = Ability.new(current_user)
  end

  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe was successfully created.'
    else
      render 'new'
    end
  end

  def show
    @recipe = Recipe.includes(recipe_foods: :food).find(params[:id])
    @inventories = Inventory.all
  end

  def new
    @recipe = Recipe.new
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: 'Recipe was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    Recipe.find(params[:id]).destroy
    redirect_to recipes_path
  end

  def update_privacy
    @recipe = Recipe.find(params[:id])
    @recipe.toggle!(:public)
    if @recipe.save
      redirect_to recipe_path(@recipe), notice: 'Recipe privacy updated.'
    else
      render 'edit'
    end
  end

  def public_recipes
    @recipes = Recipe.includes(:recipe_foods, recipe_foods: :food).where(public: true)
  end

  def shopping_list
    @recipe = Recipe.includes(recipe_foods: :food).find(params[:id])
    if params[:inventory_id] == '--Select Inventory--'
      redirect_to recipe_path(@recipe), alert: 'Please add an inventory'
    else
      @inventory = Inventory.includes(inventory_foods: :food).find(params[:inventory_id])
      @shop_list = []
      @shop_list = calculate_shopping_list(@recipe, @inventory)
      @amount = @shop_list.count
      @total_price = @shop_list.sum { |item| item[:shop_price] }
    end
  end

  def calculate_shopping_list(recipe, inventory)
    shop_list = []
    recipe.recipe_foods.each do |rf|
      i_food = inventory.inventory_foods.find_by(food: rf.food)
      if i_food.nil?
        quantity = rf.quantity
        shop_price = quantity * rf.food.price
      elsif i_food.quantity < rf.quantity
        quantity = rf.quantity - i_food.quantity
        shop_price = quantity * rf.food.price
      else
        quantity = 0
      end
      next unless quantity.positive?

      shop_list << { name: rf.food.name, quantity:, measurement_unit: rf.food.measurement_unit, shop_price: }
    end
    shop_list
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_modal.html.erb
<div id='recipe-popup' class='modal hidden'>
   <button id='close-popup'>close</button>
   <h2>Generating Shopping List</h2>
   <div class='modal-description'>
      <h3>Choose an inventory to use</h3>
      <div class='modal-generate'>
      <%= form_with model: @recipe, url: shopping_list_recipe_path, class: 'modal-form', data: { turbo: false }, method: :get do |f| %>
           <select aria-label="Default select example" name="inventory_id" class='model-select'>
             <option selected>--Select Inventory--</option>
             <% @inventories.each do |inventory| %>
               <option value="<%= inventory.id %>"><%= inventory.name %></option>
           <% end %>
           </select>
       <%= f.submit "Generate", class: "btn-generate" %>
       <% end %>
       </div>
   </div>
</div>
 

app/views/recipes/index.html.erb
<div class="bg-white p-4 md:p-6 rounded-lg shadow-md md:w-[100%] mt-3">
  <h1 class="text-3xl md:text-4xl font-semibold mb-3 md:mb-5">Welcome To Recipe Page</h1>

  <div class="mb-3 md:mb-6">
    <%= link_to new_recipe_path,
      class: "px-3 md:px-4 py-2 bg-blue-500 hover:bg-blue-600 text-white font-medium rounded-lg cursor-pointer" do %>
      Add
      <% end %>
  </div>

  <div class="recipe-container mt-3 md:mt-5">
    <% @recipes.each do |recipe| %>
      <div
        class="recipe bg-gray-100 p-3 md:p-4 rounded-lg mb-3 md:mb-4 flex flex-col md:flex-row justify-between items-center">
        <div class="flex flex-col">
        <%= link_to recipe_path(recipe), class: "info" do %>
          <h2 class="text-xl md:text-2xl font-medium mb-2 md:mb-0">
            <%= recipe.name %>
          </h2>
                    <% end %>
           <% if can? :destroy, recipe %>
            <%= form_with model: recipe, url: recipe_path(recipe), method: :delete, class: "remove mt-3 md:mt-0" do |form| %>
              <%= form.submit "Remove" ,
                class: "px-3 md:px-4 py-1 bg-red-500 hover:bg-red-600 text-white font-medium rounded-lg cursor-pointer"
                %>
                <% end %>
                <% end %>
          </div>
            <p class="text-gray-600 text-sm md:text-lg">Description: <span class="text-xs md:text-sm">
              <%= recipe.description %>
            </span>
          </p>
        
      </div>
      <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="bg-white p-6 rounded-lg shadow-md md:w-[100%] mt-3">
    <h1 class="text-3xl font-extrabold mb-5 text-gray-800">Add New Recipe</h1>

    <%= form_with model: @recipe, url: recipes_path, class: "text-gray-800" do |form| %>
        <div class="mb-4">
            <%= form.label :name, class: "text-lg font-medium" %>
                <%= form.text_field :name,
                    class: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500" %>
        </div>
        <div class="mb-4">
            <%= form.label :preparation_time, class: "text-lg font-medium" %>
                <%= form.number_field :preparation_time, step: '0.01' ,
                    class: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500" %>
        </div>
        <div class="mb-4">
            <%= form.label :cooking_time, class: "text-lg font-medium" %>
                <%= form.number_field :cooking_time, step: '0.01' ,
                    class: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500" %>
        </div>
        <div class="mb-4">
            <%= form.label :description, class: "text-lg font-medium" %>
                <%= form.text_area :description,
                    class: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500" %>
        </div>
        <div class="mb-4 add">
            <%= form.submit "Add Recipe" ,
                class: "px-4 py-2 bg-blue-500 hover:bg-blue-600 text-white font-medium rounded-lg cursor-pointer" %>
        </div>
        <% end %>
</div>

app/views/recipes/public_recipes.html.erb
<section class='public-recipes'>
    <h1>Public Recipes</h1>
    <ul class="public-recipes-list">
        <% @recipes.each do |recipe| %>
        <%= link_to recipe_path(recipe.id) do %> 
            <li class="public-item">
                <div class = "author-container">
                    <h2 class="public-title"><%=recipe.name%></h2>
                    <h3 class="public-author"><%=recipe.user.name%></h3>
                </div>
                <div>
                    <div >Total food items: <%= recipe.recipe_foods.count%></div>
                    <div >Total price $ <%= recipe.total_price %> </div>
                </div>
                <% if can? :destroy, recipe %>
                <%= button_to "Delete", recipe, method: :delete, class: "p-delete",data: { confirm: 'Are You sure?' } %>
                <% end %>
            </li>
        <% end %> 
        <% end %>
      </ul>
</section>

app/views/recipes/shopping_list.html.erb
<section class='shopping-list'>
    <h1>Shopping List</h1>
    <div class='sl-description'>
        <div class='sl-d-label'>
            <h3>Amount of food to buy: <%=@amount %> </h3>
            <h3>Recipe: <%=@recipe.name %> </h3>
        </div>
        <div class='sl-d-label'>
        <h3>Total value of food needed: $<%= @total_price%> </h3>
        <h3>Inventory: <%=@inventory.name %> </h3>
        </div>
    </div>
    <table class='sl-table'>
        <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Price</th>
        </tr> 
        <% @shop_list.each do |item| %>
            <tr>
              <td><%= item[:name] %></td>
              <td><%= item[:quantity] %> <%= item[:measurement_unit] %></td>
              <td>$<%= item[:shop_price] %></td>
            </tr>
        <% end %>
  </table>
</section>

app/views/recipes/show.html.erb
<% if can? :read, @recipe %>
<div class="container mx-auto p-4">
  <div class="bg-white p-6 rounded-lg shadow-md mt-4 lg:w-1/2 mx-auto">
    <div class="bg-slate-400 p-6 text-slate-900 flex justify-center items-center flex-col">
      <h1 class="text-3xl font-semibold flex items-center justify-center">
        <%= @recipe.name %>
      </h1>
      <p class="text-xl mt-4">
        Preparation time: <%= @recipe.preparation_time %> hour
      </p>
      <div class="flex items-center justify-end space-x-4">
        <% if user_signed_in? %>
          <%= form_for @recipe, url: update_recipe_privacy_recipe_path(@recipe), method: :patch do |f| %>
            <% if can? :update, @recipe %>
            <div class="field mt-2 flex items-center space-x-3">
              <div class="text-lg font-medium text-gray-800">Public</div>
              <%= f.check_box :public, class: 'toggle-checkbox', onclick: 'this.form.submit();' %>
            </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <p class="text-xl">
        Cooking time: <%= @recipe.cooking_time %> hours
      </p>
      <p class="text-xl mt-4">
        Description: <%= @recipe.description %>
      </p>
      <% if can? :update, @recipe %>
      <div class="flex gap-5 mt-4 bg-slate-100 p-6 rounded-lg shadow-md">
          <button class="bg-blue-500 text-white px-4 py-2 rounded text-xs lg:text-base hover:bg-blue-600" id="open-popup">Generate Shopping List</button>
          <%= link_to new_recipe_food_path(recipe_id: @recipe.id) do %>
            <button class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 text-xs lg:text-base">Add Ingredient</button>
          <% end %>
        </div>
      <% end %>
    </div>
    <div>
    </div>
    <%= render partial: 'modal' %>
    <div class="bg-white p-6 rounded-lg shadow-md mt-4">
  <div class="overflow-x-auto">
    <table class="min-w-full text-left text-sm font-light">
      <thead class="border-b font-medium dark:border-neutral-500">
        <tr>
          <th scope="col" class="px-6 py-4">Food</th>
          <th scope="col" class="px-6 py-4">Quantity</th>
          <th scope="col" class="px-6 py-4">Value</th>
          <% if can? :destroy, @recipe %>
            <th scope="col" class="px-6 py-4">Actions</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @recipe.recipe_foods.each do |food| %>
          <tr class="border-b transition duration-300 ease-in-out hover-bg-neutral-100 dark:border-neutral-500 dark:hover-bg-neutral-600">
            <td class="whitespace-nowrap px-6 py-4"><%= food.food.name %></td>
            <td class="whitespace-nowrap px-6 py-4"><%= "#{food.quantity} #{food.food.measurement_unit}" %></td>
            <td class="whitespace-nowrap px-6 py-4">$<%= food.food.price * food.quantity %></td>
            <td class="whitespace-nowrap px-6 py-4 cursor-pointer">
              <% if can? :destroy, @recipe %>
              <div class="remove">
                <%= form_with model: food, url: recipe_food_path(food), method: :delete do |form| %>
                  <%= form.submit "Remove", class: "px-4 bg-red-500 hover-bg-red-600 text-white font-medium rounded cursor-pointer" %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

  </div>
</div>
<% else %>
 <%= link_to 'See Public Recipe', public_recipes_path %>
<% end %>