config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  resources :recipes, only: [:create, :index, :destroy, :show, :new, :update] do 
    member do
      patch 'update_privacy', to: 'recipes#update_privacy', as: 'update_recipe_privacy'
      get '/shopping_list', to:'recipes#shopping_list', as: :shopping_list
    end
  end

  resources :recipe_foods, only: [:new, :create, :destroy]

  resources :inventories, only: [:create, :index, :show, :destroy, :new] do
    resources :inventory_foods, only: [:new, :create, :destroy]
  end

  resources :inventory_foods do
    delete 'remove_food', on: :member
  end

  get '/public_recipes', to:'recipes#public_recipes', as: :public_recipes

  resources :foods, only: [:index, :create, :destroy, :new]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "recipes#public_recipes"
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :food, class_name: 'Food'
  belongs_to :recipe, class_name: 'Recipe'
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!

  def new
    @recipe_food = RecipeFood.new
    @recipe = Recipe.find(params[:recipe_id])
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.build(recipe_food_params)

    if @recipe_food.save
      redirect_to recipe_path(@recipe), notice: 'Recipe Food was successfully created.'
    else
      render 'new'
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to recipe_path(@recipe_food.recipe), notice: 'Recipe Food was successfully destroyed.'
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/new.html.erb
<div class="bg-white p-6 rounded-lg shadow-md w-[100%] mt-3">
    <h1 class="text-3xl font-extrabold mb-5 text-gray-800">Recipe Food Create</h1>

    <%= form_with model: [@recipe, @recipe_food], url: recipe_foods_path(@recipe), method: :post, class: "text-gray-800" do |form| %>
        <%= hidden_field_tag :recipe_id, @recipe.id %>

            <div class="mb-4">
                <%= form.label :food_id, class: "text-lg font-medium" %>
                    <%= form.collection_select :food_id, Food.all, :id, :name, {},
                        class: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500" %>
            </div>

            <div class="mb-4">
                <%= form.label :quantity, class: "text-lg font-medium" %>
                    <%= form.number_field :quantity,
                        class: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500" %>
            </div>

            <div class="mb-4 create">
                <%= form.submit "Create Recipe Food" ,
                    class: " bg-blue-500 hover:bg-blue-600 text-white font-medium rounded-lg cursor-pointer" %>
            </div>
            <% end %>
</div>